### ISSUE TITLE
Hello there. First of all, thank you very much for sharing. I have some problems when I run the code, I hope I can get your help.

### ISSUE THREAD

**Issue by q1178847289** [JackwithWilshere/Facial_Attributes_Multi-task#1]
Namespace(batchSize=32, gpu='7', lr=0.001, nepoch=10, workers=2)
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCGeneral.cpp line=70 error=30 : unknown error
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    model.cuda()
  File "/home/lyp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/lyp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/home/lyp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/home/lyp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/THCGeneral.cpp:70

**Comment by espectre** [comment]
I'm very sorry that I didn't realized your problem.May It is because the version of your PyTorch ,and you can refer to the discussion in this link:[https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-30-unknown-error/10100/7](url)
